const studentsData = [
  {
    id: 2101264,
    name: "MOUREY JAMES M. PANTANOSAS",
    age: 21,
    program: "BSIT",
    yearLevel: 3,
    gender: "MALE",
  },
  {
    id: 2101265,
    name: "ELLA JOHNSON",
    age: 20,
    program: "BSCS",
    yearLevel: 2,
    gender: "FEMALE",
  },
  {
    id: 2101266,
    name: "ADAM SMITH",
    age: 22,
    program: "BBA",
    yearLevel: 4,
    gender: "MALE",
  },
  {
    id: 2101267,
    name: "SOPHIA GARCIA",
    age: 19,
    program: "BA English",
    yearLevel: 1,
    gender: "FEMALE",
  },
  {
    id: 2101268,
    name: "NOAH MARTINEZ",
    age: 23,
    program: "Biology",
    yearLevel: 4,
    gender: "MALE",
  },
  {
    id: 2101269,
    name: "OLIVIA BROWN",
    age: 20,
    program: "Psychology",
    yearLevel: 2,
    gender: "FEMALE",
  },
  {
    id: 2101270,
    name: "LIAM WILSON",
    age: 21,
    program: "Mechanical Engineering",
    yearLevel: 3,
    gender: "MALE",
  },
  {
    id: 2101271,
    name: "EMMA ANDERSON",
    age: 20,
    program: "Nursing",
    yearLevel: 2,
    gender: "FEMALE",
  },
  {
    id: 2101272,
    name: "AIDEN THOMPSON",
    age: 22,
    program: "Chemistry",
    yearLevel: 4,
    gender: "MALE",
  },
  {
    id: 2101273,
    name: "AVA HERNANDEZ",
    age: 19,
    program: "Art History",
    yearLevel: 1,
    gender: "FEMALE",
  },
];

export default studentsData;
